.github/actions/check-pr: '.github/actions/check-pr/**/*.js'
.github/actions/changes: '.github/actions/changes/**/*.js'
.github/actions/setup-environment: '.github/actions/setup-environment/**/*.js'
.github/actions/release: '.github/actions/release/**/*.js'
workflows: '.github/workflows/**'
uv: 'uv.lock'
framework: 'framework/**'
common: 'common/**'
command-line-interface: 'command-line-interface/**'
editor-support: 'editor-support/!(clients)/**'
editor-support/clients/vscode: 'editor-support/clients/vscode/**'
docs: 'docs/**'
extras/async-messaged: 'extras/async-messaged/**'
