name: setup-ibm-mqm
description: Install IBM MQM client redist libraries
inputs:
  image:
    description: 'Image running'
    required: true

runs:
  using: "composite"
  steps:
  - name: "Install IBM-MQC-Redist-LinuxX64"
    if: inputs.image == 'ubuntu-latest'
    env:
      GRIZZLY_TMP_DIR: ${{ env.GRIZZLY_TMP_DIR }}
    shell: bash
    run: |
      mkdir -p $GRIZZLY_TMP_DIR/mqm
      pushd $GRIZZLY_TMP_DIR/mqm &>/dev/null
      wget --no-verbose https://ibm.biz/IBM-MQC-Redist-LinuxX64targz -O - | tar xzf -
      popd &>/dev/null

  - name: "Setup environment"
    if: inputs.image == 'ubuntu-latest'
    uses: ./.github/actions/setup-environment
    with:
      add-env: |
        LD_LIBRARY_PATH=${{ env.GRIZZLY_TMP_DIR }}/mqm/lib64
        MQ_FILE_PATH=${{ env.GRIZZLY_TMP_DIR }}/mqm

