name: setup-ibm-mqm
description: Install IBM MQM client redist libraries
inputs:
  image:
    description: 'Image running'
    required: true

runs:
  using: "composite"
  steps:
  - name: "Install IBM-MQC-Redist-LinuxX64"
    if: inputs.image == 'ubuntu-latest'
    env:
      GRIZZLY_TMP_DIR: ${{ env.GRIZZLY_TMP_DIR }}
    shell: bash
    run: |
      mkdir -p $GRIZZLY_TMP_DIR/mqm
      pushd $GRIZZLY_TMP_DIR/mqm &>/dev/null
      wget --no-verbose https://ibm.biz/IBM-MQC-Redist-LinuxX64targz -O - | tar xzf -
      popd &>/dev/null

      ./extras/scripts/setup-environment.py \
        --add-env LD_LIBRARY_PATH=$GRIZZLY_TMP_DIR/mqm/lib64 \
        --add-env MQ_FILE_PATH=$GRIZZLY_TMP_DIR/mqm

