nav:
  - index.md
  - example.md
  - code_of_conduct.md
  - Framework:
    - Usage:
      - Tasks:
          - Clients:
      - Variables:
        - framework/usage/variables/environment-configuration.md
        - Testdata:
        - framework/usage/variables/templating.md
      - Load Users:
      - Steps:
        - Background:
        - Scenario:
    - Changelog: framework/changelog.md
    - Licenses: framework/licenses.md
  - Command Line Interface:
    - Usage:
      - command-line-interface/usage/index.md
      - Metadata: command-line-interface/usage/metadata.md
    - Changelog: command-line-interface/changelog.md
    - Licenses: command-line-interface/licenses.md
  - Editor support:
    - editor-support/index.md
    - Language server: editor-support/language-server.md
    - Editors:
      - editor-support/editors/index.md
      - Visual Studio Code: editor-support/editors/vscode.md
    - Changelog: editor-support/changelog.md
    - Licenses: editor-support/licenses.md
